shop/cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

shop/orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.order_create, name='order_create'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('cart', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/cart/models.py
from django.db import models

# Create your models here.

shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import ProcessorCharacteristics
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(ProcessorCharacteristics, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('product_page', product.name)


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(ProcessorCharacteristics, id=product_id)

    cart.remove(product)

    return redirect('/cart')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

shop/cart/templates/cart/detail.html
{% extends "main/layout.html" %}
{% block title %} Ваша корзина {% endblock %}
{% block content %}
<h1>Ваша корзина</h1>
<table class="table table-dark">
    <thead>
    <tr>
        <th>Продукт</th>
        <th>Фото</th>
        <th>Количество</th>
        <th>Цена, шт</th>
        <th>Полная цена</th>
        <th>Удалить</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
        {% with product=item.product %}
            <tr>
              <td>{{ product.name }}</td>
              <td>
                  <a href="{{ product.name }}">
                    <img src="static/main/img/processors_images/{{product.img}}.jpg" alt="{{ product.name }}" height="200px"
                    width="200px">
                  </a>
              </td>
              <td>{{ item.quantity }}</td>
              <td>${{ item.price }}</td>
              <td>${{ item.total_price }}</td>
              <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
            </tr>
        {% endwith %}
    {% endfor %}
    <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td>${{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>
<div class="text-right" style="margin: 10px; padding-bottom:30px;">
    <a href="{% url 'home' %}" class="btn" style="background-color: gray; color: white;">Продолжить покупки</a>
    <a href="{% url 'orders:order_create' %}" class="btn btn-success btn-send">Заказать</a>
</div>
{% endblock %}