shop/cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

shop/main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name = 'home'),
    path('filtred', views.filtred, name = 'filtred'),
    path('<str:product_name>', views.product_page, name = 'product_page'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('cart', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/users/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('login', views.user_login, name = 'login'),
    path('registration', views.user_registration, name = 'registration'),
    path('logout', views.user_logout, name = 'logout'),
]

shop/main/models.py
from django.db import models

class ProcessorCharacteristics(models.Model):
    name = models.TextField()
    number_of_cores = models.PositiveSmallIntegerField()
    processor_technology = models.PositiveSmallIntegerField()
    base_clock = models.PositiveSmallIntegerField()
    thermal_design_power = models.PositiveSmallIntegerField()
    cache_memory = models.TextField()
    integrated_graphics_core = models.TextField()
    img = models.TextField()
    units_in_stock = models.PositiveSmallIntegerField()
    price = models.PositiveSmallIntegerField()


    @staticmethod
    def core_filter(list):
        if len(list) == 0 or len(list) == 2:
            return ProcessorCharacteristics.objects.all()
        else:
            return ProcessorCharacteristics.objects.filter(integrated_graphics_core__contains=list[0])


    @staticmethod
    def pack_filter(list):
        if len(list) == 0 or len(list) == 2:
            return ProcessorCharacteristics.objects.all()
        else:
            return ProcessorCharacteristics.objects.filter(name__contains=list[0])


    @staticmethod
    def name_filter(list):
        if len(list) == 0:
            return ProcessorCharacteristics.objects.filter(name__contains = 'None')
        result = ProcessorCharacteristics.objects.filter(name__contains=list[-1])
        list.pop(-1)
        return result | ProcessorCharacteristics.name_filter(list)

shop/main/views.py
from django.shortcuts import render
from .models import ProcessorCharacteristics as PC
from django.core.paginator import Paginator
from cart.forms import CartAddProductForm

def index(request):
    proc_data = Paginator(PC.objects.all(), 30)
    page_number = request.GET.get('page')
    page_obj = proc_data.get_page(page_number)

    data = {
        'page_obj' : page_obj,
        'page_number': page_number,
        }

    return render(request, 'main/index.html', data)


def filtred(request):
    core_list = request.GET.getlist('filter_by_core')
    pack_list = request.GET.getlist('filter_by_pack')
    name_list = request.GET.getlist('filter_by_name')

    if len(name_list) > 0:
        final_filter  = PC.core_filter(core_list) & PC.pack_filter(pack_list) & PC.name_filter(name_list)
    else:
        final_filter = PC.core_filter(core_list) & PC.pack_filter(pack_list)

    filtred_page = Paginator(final_filter, 1000).get_page(1)

    if len(filtred_page.object_list) == 0:
        is_empty = True
    else:
        is_empty = False

    data = {
        'filtred_page' : filtred_page,
        'is_empty' : is_empty,
        }

    return render(request, 'main/filtred.html', data)


def product_page(request, product_name:str):
    product = PC.objects.get(name__contains = product_name)
    cart_product_form = CartAddProductForm()

    data = {
        'product': product,
        'cart_product_form': cart_product_form,
        }
    return render(request, 'main/product_page.html', data)

shop/main/templates/main/filtred.html
{% extends 'main/layout.html' %}

{% block title %}Топовые процессоры по низким ценам{% endblock %}

{% block content %}
<link rel="stylesheet" href='static/main/css/index.css'>
<!--  CSS и JS слайдера -->
<link rel="stylesheet" href='static/main/css/slider.css'>
<script defer src='static/main/js/slider.js'></script>
<!-- Cлайдер -->
<div class="slider">
	<div class="item"> <img src="static/main/img/slider/1.jpg"> </div>
	<div class="item"> <img src="static/main/img/slider/2.jpg"> </div>
	<div class="item"> <img src="static/main/img/slider/3.jpg"> </div>
	<!-- Кнопки-стрелочки --><a class="previous" onclick="previousSlide()">&#10094;</a> <a class="next" onclick="nextSlide()">&#10095;</a> </div>
<!-- Фильтры -->
<div class="row">
  <div class="col-xs-3 col-p-v site-body-aside">
  	<div class="row">
			<form  method="GET" action="{% url 'filtred' %}">
			  {% csrf_token %}
  			<div class="form-group row">
  				<div class="col-sm-2">Интегрированное графическое ядро:</div>
  				<br>
  				<div class="col-sm-10">
  					<div class="form-check">
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_core" value="МГц">
  						<label class="form-check-label" for="gridCheck1"> Есть </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_core" value="-">
  						<label class="form-check-label" for="gridCheck1"> Нету </label>
  					</div>
  				</div>
  			</div>
  			<div class="form-group row">
  				<div class="col-sm-2">Тип поставки:</div>
  				<br>
  				<div class="col-sm-10">
  					<div class="form-check">
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_pack" value="BOX">
  						<label class="form-check-label" for="gridCheck1"> BOX </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_pack" value="OEM">
  						<label class="form-check-label" for="gridCheck1"> OEM </label>
  					</div>
  				</div>
  			</div>
  			<div class="form-group row">
  				<div class="col-sm-2">Семейство:</div>
  				<br>
  				<div class="col-sm-10">
  					<div class="form-check">
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_name" value="Athlon">
  						<label class="form-check-label" for="gridCheck1"> Athlon </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_name" value="Ryzen 3">
  						<label class="form-check-label" for="gridCheck1"> Ryzen 3 </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_name" value="Ryzen 5">
  						<label class="form-check-label" for="gridCheck1"> Ryzen 5 </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_name" value="Ryzen 9">
  						<label class="form-check-label" for="gridCheck1"> Ryzen 9 </label>
  					</div>
  				</div>
					<input type="submit" class="btn btn-success btn-send" value="Найти">
  			</div>
			</form
  	</div>
  </div>
</div>
	<!-- Сетка для товаров -->
	<div class="col-xs-9 col-p-v site-body-main">
		<div class="row">
			{% for proc in filtred_page %}
		    <div class="col-sm"> <img src="static/main/img/processors_images/{{proc.img}}.jpg" alt="{{proc.name}}">
			  	<a href="/{{proc.name}}" class="product-name">Процессор {{proc.name}}</a>
			  	<p class="product-description">Основные характеристики: {{proc.number_of_cores}}-ядерный процессор, {{proc.base_clock}} МГц, техпроцесс {{proc.processor_technology}} нм, тепловыделение {{proc.thermal_design_power}} Вт, объем кэша L1/L2/L3: {{proc.cache_memory}}</p>
					<p class="product-description" style="font-weight: bold;">Цена: {{ proc.price}}$</p></div>
		  {% endfor %}

      {% if is_empty %}
        <h2>По вашим фильтрам ничего не найдено :(</h2>
      {% endif %}
		</div>
  </div>
{% endblock %}

shop/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block title %}Топовые процессоры по низким ценам{% endblock %}

{% block content %}
<link rel="stylesheet" href='static/main/css/index.css'>
<!--  CSS и JS слайдера -->
<link rel="stylesheet" href='static/main/css/slider.css'>
<script defer src='static/main/js/slider.js'></script>
<!-- Cлайдер -->
<div class="slider">
	<div class="item"> <img src="static/main/img/slider/1.jpg"> </div>
	<div class="item"> <img src="static/main/img/slider/2.jpg"> </div>
	<div class="item"> <img src="static/main/img/slider/3.jpg"> </div>
	<!-- Кнопки-стрелочки --><a class="previous" onclick="previousSlide()">&#10094;</a> <a class="next" onclick="nextSlide()">&#10095;</a> </div>
<!-- Фильтры -->
<div class="row">
  <div class="col-xs-3 col-p-v site-body-aside">
  	<div class="row">
			<form  method="GET" action="{% url 'filtred' %}">
			  {% csrf_token %}
  			<div class="form-group row">
  				<div class="col-sm-2">Интегрированное графическое ядро:</div>
  				<br>
  				<div class="col-sm-10">
  					<div class="form-check">
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_core" value="МГц">
  						<label class="form-check-label" for="gridCheck1"> Есть </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_core" value="-">
  						<label class="form-check-label" for="gridCheck1"> Нету </label>
  					</div>
  				</div>
  			</div>
  			<div class="form-group row">
  				<div class="col-sm-2">Тип поставки:</div>
  				<br>
  				<div class="col-sm-10">
  					<div class="form-check">
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_pack" value="BOX">
  						<label class="form-check-label" for="gridCheck1"> BOX </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_pack" value="OEM">
  						<label class="form-check-label" for="gridCheck1"> OEM </label>
  					</div>
  				</div>
  			</div>
  			<div class="form-group row">
  				<div class="col-sm-2">Семейство:</div>
  				<br>
  				<div class="col-sm-10">
  					<div class="form-check">
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_name" value="Athlon">
  						<label class="form-check-label" for="gridCheck1"> Athlon </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_name" value="Ryzen 3">
  						<label class="form-check-label" for="gridCheck1"> Ryzen 3 </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_name" value="Ryzen 5">
  						<label class="form-check-label" for="gridCheck1"> Ryzen 5 </label>
  						<input class="form-check-input" type="checkbox" id="gridCheck1" name="filter_by_name" value="Ryzen 9">
  						<label class="form-check-label" for="gridCheck1"> Ryzen 9 </label>
  					</div>
  				</div>
					<input type="submit" class="btn btn-success btn-send" value="Найти">
  			</div>
			</form
  	</div>
  </div>
</div>
	<!-- Сетка для товаров -->
	<div class="col-xs-9 col-p-v site-body-main">
		<div class="row">
			{% for proc in page_obj %}
		    <div class="col-sm"> <img src="static/main/img/processors_images/{{proc.img}}.jpg" alt="{{proc.name}}">
			  	<a href="/{{proc.name}}" class="product-name">Процессор {{proc.name}}</a>
			  	<p class="product-description">Основные характеристики: {{proc.number_of_cores}}-ядерный процессор, {{proc.base_clock}} МГц, техпроцесс {{proc.processor_technology}} нм, тепловыделение {{proc.thermal_design_power}} Вт, объем кэша L1/L2/L3: {{proc.cache_memory}}.</p>
					<p class="product-description" style="font-weight: bold;">Цена: {{ proc.price}}$</p></div>
		  {% endfor %}
		</div>
		<div class="row form-group" style="padding-bottom: 5%;">
				{% if page_obj.has_previous %}
					{%  if page_obj.previous_page_number > 2 %}
						<a href="?page={{ 1 }}" class="col-xs-3 page-link">{{ 1 }}</a><a href="?page={{ 1 }}" class="col-xs-3 page-link">...</a>
					{% endif %}
					<a href="?page={{ page_obj.previous_page_number }}" class="col-xs-3 page-link">{{ page_obj.previous_page_number }}</a>
					<a href="?page={{ page_number }}" class="col-xs-3 page-link" style='background-color: white;'>{{ page_number }}</a>
					{% if page_obj.has_next %}
						<a href="?page={{ page_obj.next_page_number }}" class="col-xs-3 page-link">{{ page_obj.next_page_number }}</a>
					{% endif %}
				{% elif page_obj.has_next %}
					<a href="?page={{ 1 }}" class="col-xs-3 page-link" style='background-color: white;'>{{ 1 }}</a>
					<a href="?page={{ 2 }}" class="col-xs-3 page-link">{{ 2 }}</a>
					<a href="?page={{ 3 }}" class="col-xs-3 page-link">{{ 3 }}</a>
				{% endif %}
		</div>
  </div>
{% endblock %}

shop/main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
  <script src="https://kit.fontawesome.com/9af9b5cee5.js" crossorigin="anonymous"></script>
</head>
<body>
  <header>
    <div class="logo">
      <a href="/">
        <img src="{% static 'main/img/logo.png' %}" width="240" height="60px" />
      </a>
    </div>
    <div class="menu">
      <ul>
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'cart:cart_detail' %}">{{ cart|length }} <i class="fa-solid fa-basket-shopping"></i> {{ user.get_username }}</a></li>
        <li><a href="{% url 'users:logout' %}">Выйти</a></li>
        {% else %}
        <li><a href="{% url 'users:login' %}"><i class="fa-solid fa-user"></i>Вход</a><a href="{% url 'users:registration' %}">\Регистрация</a></li>
        <li><a href="{% url 'cart:cart_detail' %}">{{ cart|length }} <i class="fa-solid fa-basket-shopping"></i>Корзина</a></li>
        {% endif %}
      </ul>
    </div>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

shop/main/templates/main/product_page.html
{% extends 'main/layout.html' %}

{% block title %} Купить {{ product.name}}{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm">
			<br>
			<h2>Процессор {{ product.name }}</h2>
			<br> <img src="static\main\img\processors_images\{{product.img}}.jpg" alt="product.name" height="400px" width="400px"> </div>
		<div class="col-sm">
			<div style="padding-bottom: 20px; padding-left: 20px; background-color: grey;">
				<ul style="margin-top: 20%; font-size: 26px">Основные характеристики:
					<li>Число ядер - {{product.number_of_cores}}</li>
					<li>Частота - {{product.base_clock}} МГц</li>
					<li>Техпроцесс - {{product.processor_technology}} нм</li>
					<li>Тепловыделение - {{product.thermal_design_power}} Вт</li>
					<li>Объем кэша L1/L2/L3 {{product.cache_memory}}</li>
					<li>Интегрированное графическое ядро {{ product.integrated_graphics_core }}</li>
				</ul>
				<h3 style="font-weight: bold">Количество на складе: {{ product.units_in_stock}} шт</h3>
				<br>
				<h3 style="font-weight: bold">${{ product.price }}</h3>
				<form action="{% url 'cart:cart_add' product.id %}" method="post">
					{{ cart_product_form }}
					{% csrf_token %}
					<input class="btn btn-success btn-sendt" type="submit" value="Добавить в корзину">
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}